# Final Project

In [1]:
import data_extraction

In [16]:
# Encode and run query to get match data for The International
query = """
SELECT 
    m.*,
    l.name as league_name,
    l.leagueid
FROM matches m
JOIN leagues l USING(leagueid)
WHERE l.name ILIKE 'The International%'
ORDER BY m.start_time DESC
"""

encoded_query = data_extraction.encode_query(query)
base_url = "https://api.opendota.com/api/explorer"
params = {"sql": encoded_query}

match_data = data_extraction.get_api_data(base_url, params=params)

In [17]:
match_data.groupby('league_name').size().sort_values(ascending=False)

league_name
The International 2017                           540
The International 2021                           487
The International 2019                           461
The International 2014                           416
The International 2015                           409
The International 2018                           401
The International 2016                           398
The International 2022                           231
The International 2013                           162
The International 2012                           154
The International 2023                           151
The International 2024                           121
The International 2022 Last Chance Qualifiers    103
The International East Qualifiers                 40
The International West Qualifiers                 39
dtype: int64

In [18]:
match_data[match_data['league_name'] == 'The International 2024']

,match_id,match_seq_num,radiant_win,start_time,duration,tower_status_radiant,tower_status_dire,barracks_status_radiant,barracks_status_dire,cluster,...,teamfights,version,cosmetics,radiant_score,dire_score,draft_timings,series_id,series_type,replay_salt,league_name
0,7944311818,6683523584,False,1726415990,2068,0,2046,0,63,187,...,"[{'start': 720, 'end': 766, 'last_death': 751,...",21.0,"{'600': 129, '647': 3, '6758': 1, '6997': 3, '...",17,34,"[{'order': 1, 'pick': False, 'active_team': 3,...",905925,2,1960134483,The International 2024
1,7944174632,6683426559,True,1726411205,2649,1958,0,63,0,187,...,"[{'start': 813, 'end': 859, 'last_death': 844,...",21.0,"{'647': 131, '5939': 3, '6857': 128, '7459': 1...",22,12,"[{'order': 1, 'pick': False, 'active_team': 3,...",905925,2,1003157839,The International 2024
2,7944065089,6683315510,False,1726407415,1767,512,2036,0,63,185,...,"[{'start': 306, 'end': 340, 'last_death': 325,...",21.0,"{'600': 129, '647': 1, '5145': 3, '5266': 4, '...",15,24,"[{'order': 1, 'pick': False, 'active_team': 3,...",905925,2,1045213686,The International 2024
3,7943810234,6683152655,True,1726397145,4145,1956,0,63,0,185,...,"[{'start': 272, 'end': 319, 'last_death': 304,...",21.0,"{'647': 129, '5145': 3, '5588': 4, '6857': 0, ...",47,30,"[{'order': 1, 'pick': False, 'active_team': 3,...",905818,1,638789246,The International 2024
4,7943704335,6683039107,False,1726392921,1818,4,2038,3,63,185,...,"[{'start': 789, 'end': 833, 'last_death': 818,...",21.0,"{'647': 2, '5105': 129, '6687': 0, '6758': 0, ...",13,29,"[{'order': 1, 'pick': False, 'active_team': 3,...",905818,1,1855885625,The International 2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
116,7927715273,6669894721,True,1725441709,2113,1920,260,55,63,185,...,"[{'start': 39, 'end': 74, 'last_death': 59, 'd...",21.0,"{'600': 2, '647': 129, '4624': 130, '4801': 3,...",25,28,"[{'order': 1, 'pick': False, 'active_team': 3,...",903379,3,1682786811,The International 2024
117,7927711289,6669889884,True,1725441699,1716,1983,1536,63,1,185,...,"[{'start': 482, 'end': 529, 'last_death': 514,...",21.0,"{'647': 130, '4016': 2, '5335': 2, '6646': 128...",35,11,"[{'order': 1, 'pick': False, 'active_team': 3,...",903380,3,433232873,The International 2024
118,7927665226,6669859354,False,1725437673,2475,0,1958,0,63,187,...,"[{'start': 564, 'end': 612, 'last_death': 597,...",21.0,"{'647': 129, '5445': 128, '5713': 130, '6833':...",33,33,"[{'order': 1, 'pick': False, 'active_team': 3,...",903378,3,1102943036,The International 2024
119,7927665254,6669856807,False,1725437485,2379,0,1972,0,63,185,...,"[{'start': 822, 'end': 860, 'last_death': 845,...",21.0,"{'647': 130, '5588': 132, '7459': 3, '7527': 1...",21,22,"[{'order': 1, 'pick': False, 'active_team': 3,...",903380,3,210510080,The International 2024
120,7927665228,6669857214,True,1725437441,2438,1536,390,28,59,185,...,"[{'start': 895, 'end': 934, 'last_death': 919,...",21.0,"{'647': 1, '4317': 128, '4448': 132, '5832': 1...",15,16,"[{'order': 1, 'pick': False, 'active_team': 3,...",903379,3,565671108,The International 2024

In [11]:
league_data.loc[league_data['name'].str.contains('the international', case=False)]

,leagueid,ticket,banner,tier,name
410,600,None,None,professional,The International 2014
767,2733,None,None,professional,The International 2015
787,11625,None,None,premium,The International 10
901,4664,None,None,premium,The International 2016
1738,15728,None,None,premium,The International 2023
2139,4768,None,None,excluded,The International 2016 Open Qualifiers
2334,5401,None,None,professional,The International 2017
2536,65005,econ/leagues/subscriptions_westqualifier_ingame,econ/leagues/subscriptions_westqualifier_ingame,professional,The International West Qualifiers
2627,65004,econ/leagues/subscriptions_eastqualifier_ingame,econ/leagues/subscriptions_eastqualifier_ingame,professional,The International East Qualifiers
3402,16839,None,None,professional,Road To The International 2024 - Regional Qual...
3403,16843,None,None,professional,Road To The International 2024 - Regional Qual...
3404,16844,None,None,professional,Road To The International 2024 - Regional Qua...
3861,13256,None,None,premium,The International 2021
4115,14268,None,None,premium,The International 2022
5277,16841,None,None,professional,Road To The International 2024 - Regional Qua...
5279,16842,None,None,professional,Road To The International 2024 - Regional Qua...
5321,16840,None,None,professional,Road To The International 2024 - Regional Qua...
5430,9870,None,None,premium,The International 2018
5823,10749,None,None,premium,The International 2019
5905,11090,None,None,excluded,The International 2019 Open Qualifiers
6993,65001,econ/leagues/subscriptions_international_ingame,econ/leagues/subscriptions_international_ingame,professional,The International 2012
7013,14642,None,None,premium,The International 2022 Last Chance Qualifiers
7290,10049,None,None,excluded,The International 2018 Open Qualifiers
7513,16935,None,None,premium,The International 2024
7741,65006,None,None,professional,The International 2013

In [12]:
# get the matches from the internationals

In [13]:
# tier the heroes

In [14]:
# some plots about the heroes

In [15]:
#teams, some background